apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - briantopping/jx3-infra
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - briantopping/jx3-project-test
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/config.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      briantopping/jx3-infra:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - size
      - trigger
      - wip
      - heart
      - cat
      - override
      - dog
      - pony
      briantopping/jx3-project-test:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - briantopping/jx3-infra
      trusted_org: briantopping
    - repos:
      - briantopping/jx3-project-test
      trusted_org: briantopping
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
